---
kind: pipeline
type: docker
name: default
steps:
- name: yaml_lint
  image: sdesbure/yamllint:latest
  commands:
  - yamllint -d relaxed .drone.yml
- name: dockerfile_lint
  image: hadolint/hadolint:v1.18.1
  commands:
  - hadolint --ignore DL3033 centos6/Dockerfile
  - hadolint --ignore DL3033 centos7/Dockerfile
